version: "3.8"

services:
  airflow:
    build:
      context: .
      dockerfile: dockerfile.airflow
    container_name: pipeline_02_airflow
    restart: always
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      BASE_OUTPUT: data/processed/airflow
    user: "${AIRFLOW_UID}:0"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/project/data
      - ./spark_job:/opt/airflow/project/spark_job
      - ./requirements.txt:/opt/airflow/project/requirements.txt
    ports:
      - "8080:8080"
    command: 
      - bash 
      - -c 
      - |
        pip install -r /opt/airflow/project/requirements.txt
        airflow db init
        airflow users create \
          --username admin \
          --password admin \
          --firstname admin \
          --lastname admin \
          --role Admin \
          --email admin@example.com || true
        airflow scheduler & 
        airflow webserver
  
